title: My Jekyll
description: >
  My Description. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
baseurl: ""
url: "http://e-joint.jp"

author:
  name: Yuma Uchiumi
  email: yumaloop@gmail.com
  github: yumaloop
  twitter: yumaloop
  facebook: uchiumiyuma
  disqus_shortname: https-yumaloop-github-io

paginate: 3
paginate_path: page:num

sass:
  style: expanded

plugins:
  - jekyll-paginate
  - jekyll-feed
